/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign application.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Request for the /1/object/apikey/createObject API Request
 */
export interface ApikeyCreateObjectV1Request {
    objApikey?: models.ApikeyRequest;

    objApikeyCompound?: models.ApikeyRequestCompound;

}
