/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.48
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Payload for the /1/object/ezsigndocument/{pkiEzsigndocumentID}/getWordsPositions API Request
 */
export interface EzsigndocumentGetWordsPositionsV1ResponseMPayload {
    /**
     * An array of words with an array of pages and positions X,Y  They are returned with the sames words that was sent in the request.
     */
    a_sWords: Array<models.WordPositionResponse>;

}
