/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.31
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Request for the /1/object/ezsignfoldersignerassociation/editObject API Request
 */
export interface UNUSEDEzsignfoldersignerassociationEditObjectV1Request {
    objEzsignfoldersignerassociation?: models.EzsignfoldersignerassociationRequest;

}
