/**
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.32
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * A webhook object
 */
export interface WebhookResponse {
    /**
     * The Webhook ID. This value is visible in the admin interface.
     */
    pkiWebhookID: number;

    /**
     * The Module generating the Event.
     */
    eWebhookModule: WebhookResponse.EWebhookModuleEnum;

    /**
     * This Ezsign Event. This property will be set only if the Module is \"Ezsign\".
     */
    eWebhookEzsignevent?: WebhookResponse.EWebhookEzsigneventEnum;

    /**
     * The customer code assigned to your account
     */
    pksCustomerCode: string;

    /**
     * The url being called
     */
    sWebhookUrl: string;

    /**
     * The email that will receive the webhook in case all attempts fail.
     */
    sWebhookEmailfailed: string;

    /**
     * This Management Event. This property will be set only if the Module is \"Management\".
     */
    eWebhookManagementevent?: WebhookResponse.EWebhookManagementeventEnum;

}
export namespace WebhookResponse {
    export enum EWebhookModuleEnum {
        Ezsign = <any> 'Ezsign',
        Management = <any> 'Management'
    }
    export enum EWebhookEzsigneventEnum {
        DocumentCompleted = <any> 'DocumentCompleted',
        FolderCompleted = <any> 'FolderCompleted'
    }
    export enum EWebhookManagementeventEnum {
        UserCreated = <any> 'UserCreated'
    }
}
