export * from './GlobalCustomerApi';
import { GlobalCustomerApi } from './GlobalCustomerApi';
export * from './ModuleSsprApi';
import { ModuleSsprApi } from './ModuleSsprApi';
export * from './ModuleUserApi';
import { ModuleUserApi } from './ModuleUserApi';
export * from './ObjectActivesessionApi';
import { ObjectActivesessionApi } from './ObjectActivesessionApi';
export * from './ObjectApikeyApi';
import { ObjectApikeyApi } from './ObjectApikeyApi';
export * from './ObjectEzsigndocumentApi';
import { ObjectEzsigndocumentApi } from './ObjectEzsigndocumentApi';
export * from './ObjectEzsignfolderApi';
import { ObjectEzsignfolderApi } from './ObjectEzsignfolderApi';
export * from './ObjectEzsignfoldersignerassociationApi';
import { ObjectEzsignfoldersignerassociationApi } from './ObjectEzsignfoldersignerassociationApi';
export * from './ObjectEzsignsignatureApi';
import { ObjectEzsignsignatureApi } from './ObjectEzsignsignatureApi';
export * from './ObjectFranchisebrokerApi';
import { ObjectFranchisebrokerApi } from './ObjectFranchisebrokerApi';
export * from './ObjectFranchiseofficeApi';
import { ObjectFranchiseofficeApi } from './ObjectFranchiseofficeApi';
export * from './ObjectFranchisereferalincomeApi';
import { ObjectFranchisereferalincomeApi } from './ObjectFranchisereferalincomeApi';
export * from './ObjectPeriodApi';
import { ObjectPeriodApi } from './ObjectPeriodApi';
export const APIS = [GlobalCustomerApi, ModuleSsprApi, ModuleUserApi, ObjectActivesessionApi, ObjectApikeyApi, ObjectEzsigndocumentApi, ObjectEzsignfolderApi, ObjectEzsignfoldersignerassociationApi, ObjectEzsignsignatureApi, ObjectFranchisebrokerApi, ObjectFranchiseofficeApi, ObjectFranchisereferalincomeApi, ObjectPeriodApi];
